//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrPract.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Договор_энергоснабжения
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Договор_энергоснабжения()
        {
            this.Показания_прибора_учета = new HashSet<Показания_прибора_учета>();
            this.Показания_прибора_учета1 = new HashSet<Показания_прибора_учета>();
        }
    
        public int Номер_договора { get; set; }
        public int Номер_прибора_учета { get; set; }
        public int Код_абонета { get; set; }
        public int Код_представителя_компании { get; set; }
        public int Код_тарифа { get; set; }
        public System.DateTime Дата_заключения_договора { get; set; }
        public string Особые_условия { get; set; }
    
        public virtual Абонент Абонент { get; set; }
        public virtual Абонент Абонент1 { get; set; }
        public virtual Представитель_компании Представитель_компании { get; set; }
        public virtual Представитель_компании Представитель_компании1 { get; set; }
        public virtual Тариф Тариф { get; set; }
        public virtual Тариф Тариф1 { get; set; }
        public virtual Прибор_учёта Прибор_учёта { get; set; }
        public virtual Прибор_учёта Прибор_учёта1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Показания_прибора_учета> Показания_прибора_учета { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Показания_прибора_учета> Показания_прибора_учета1 { get; set; }
    }
}
