//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrPract.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Контактные_данные
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Контактные_данные()
        {
            this.Абонент = new HashSet<Абонент>();
            this.Абонент1 = new HashSet<Абонент>();
        }
    
        public int Код_контактных_данных { get; set; }
        public int Код_адреса { get; set; }
        public string Телефон { get; set; }
        public string Мобильный_Телефон { get; set; }
        public string Электронная_почта { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Абонент> Абонент { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Абонент> Абонент1 { get; set; }
        public virtual Адрес Адрес { get; set; }
        public virtual Адрес Адрес1 { get; set; }
    }
}
