//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrPract.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Паспорт
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Паспорт()
        {
            this.Личные_данные = new HashSet<Личные_данные>();
            this.Личные_данные1 = new HashSet<Личные_данные>();
        }
    
        public int Серия_паспорта { get; set; }
        public int Номер_паспорта { get; set; }
        public int Код_адреса { get; set; }
        public string Кем_выдан { get; set; }
    
        public virtual Адрес Адрес { get; set; }
        public virtual Адрес Адрес1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Личные_данные> Личные_данные { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Личные_данные> Личные_данные1 { get; set; }
    }
}
