//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrPract.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Показания_прибора_учета
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Показания_прибора_учета()
        {
            this.Акт_снятия_показаний_приборов_учета = new HashSet<Акт_снятия_показаний_приборов_учета>();
            this.Акт_снятия_показаний_приборов_учета1 = new HashSet<Акт_снятия_показаний_приборов_учета>();
        }
    
        public int Код_показаний_прибора_учета { get; set; }
        public int Номер_договора { get; set; }
        public int Предыдущие_показания { get; set; }
        public int Текущие_показания { get; set; }
        public System.DateTime Дата_снятия_показаний { get; set; }
        public bool Конечные_показания { get; set; }
        public Nullable<int> Расход { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Акт_снятия_показаний_приборов_учета> Акт_снятия_показаний_приборов_учета { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Акт_снятия_показаний_приборов_учета> Акт_снятия_показаний_приборов_учета1 { get; set; }
        public virtual Договор_энергоснабжения Договор_энергоснабжения { get; set; }
        public virtual Договор_энергоснабжения Договор_энергоснабжения1 { get; set; }
    }
}
