//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrPract.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПредставлениеПредставитель_компании
    {
        public int Код_представителя_компании { get; set; }
        public Nullable<int> Серия_паспорта { get; set; }
        public Nullable<int> Номер_паспорта { get; set; }
        public string Номер_доверенности { get; set; }
        public Nullable<System.DateTime> Дата_выдачи_доверенности { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public Nullable<System.DateTime> Дата_рождения { get; set; }
        public string Пол { get; set; }
        public string Кем_выдан { get; set; }
        public string Улица { get; set; }
        public string Дом_влад_ { get; set; }
        public Nullable<int> Квартира { get; set; }
    }
}
