//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrPract.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПредставлениеПаспорт
    {
        public int Серия_паспорта { get; set; }
        public int Номер_паспорта { get; set; }
        public string Кем_выдан { get; set; }
        public string Улица { get; set; }
        public string Дом_влад_ { get; set; }
        public Nullable<int> Квартира { get; set; }
    }
}
