//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrPract.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПредставлениеДоговоры
    {
        public int Номер_договора { get; set; }
        public System.DateTime Дата_заключения_договора { get; set; }
        public string Особые_условия { get; set; }
        public int Код_тарифа { get; set; }
        public Nullable<int> Номер_прибора_учета { get; set; }
        public string Марка { get; set; }
        public string Тип { get; set; }
        public Nullable<int> Расчетный_коэффициент { get; set; }
        public Nullable<System.DateTime> Дата_установки_введения_в_эксплуатацию__ { get; set; }
        public string Место_установки { get; set; }
        public Nullable<int> Код_абонета { get; set; }
        public Nullable<int> Серия_паспорта { get; set; }
        public Nullable<int> Номер_паспорта { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public Nullable<System.DateTime> Дата_рождения { get; set; }
        public string Пол { get; set; }
        public string Кем_выдан { get; set; }
        public string Телефон { get; set; }
        public string Мобильный_Телефон { get; set; }
        public string Электронная_почта { get; set; }
        public string Улица { get; set; }
        public string Дом_влад_ { get; set; }
        public Nullable<int> Квартира { get; set; }
        public Nullable<decimal> Площадь_жилового_дома_кв_м_ { get; set; }
        public Nullable<int> Кол_во_комнат { get; set; }
        public Nullable<int> Кол_во_проживающих_граждан { get; set; }
        public Nullable<int> Код_представителя_компании { get; set; }
        public string Фамилия_представителя { get; set; }
        public string Имя_представителя { get; set; }
        public string Отчество_представителя { get; set; }
    }
}
