//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrPract.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПредставлениеАкты
    {
        public int Код_акта_снятия_показаний_приборов_учета { get; set; }
        public Nullable<int> Номер_договора { get; set; }
        public Nullable<int> Предыдущие_показания { get; set; }
        public Nullable<int> Текущие_показания { get; set; }
        public Nullable<System.DateTime> Дата_снятия_показаний { get; set; }
        public Nullable<int> Расход { get; set; }
        public System.DateTime Дата_сдачи_акта { get; set; }
    }
}
