//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrPract.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Прибор_учёта
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Прибор_учёта()
        {
            this.Договор_энергоснабжения = new HashSet<Договор_энергоснабжения>();
            this.Договор_энергоснабжения1 = new HashSet<Договор_энергоснабжения>();
        }
    
        public int Номер_прибора_учета { get; set; }
        public string Марка { get; set; }
        public string Тип { get; set; }
        public int Расчетный_коэффициент { get; set; }
        public System.DateTime Дата_установки_введения_в_эксплуатацию__ { get; set; }
        public string Место_установки { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Договор_энергоснабжения> Договор_энергоснабжения { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Договор_энергоснабжения> Договор_энергоснабжения1 { get; set; }
    }
}
