//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrPract.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Представитель_компании
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Представитель_компании()
        {
            this.Договор_энергоснабжения = new HashSet<Договор_энергоснабжения>();
            this.Договор_энергоснабжения1 = new HashSet<Договор_энергоснабжения>();
        }
    
        public int Код_представителя_компании { get; set; }
        public int Код_личных_данных { get; set; }
        public string Номер_доверенности { get; set; }
    
        public virtual Доверенность Доверенность { get; set; }
        public virtual Доверенность Доверенность1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Договор_энергоснабжения> Договор_энергоснабжения { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Договор_энергоснабжения> Договор_энергоснабжения1 { get; set; }
        public virtual Личные_данные Личные_данные { get; set; }
        public virtual Личные_данные Личные_данные1 { get; set; }
    }
}
