//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrPract.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ставка
    {
        public int Код_ставки { get; set; }
        public int Код_тарифа { get; set; }
        public Nullable<int> Код_зоны_суток { get; set; }
        public decimal Цена_за_кВт_час { get; set; }
    
        public virtual Зона_суток Зона_суток { get; set; }
        public virtual Зона_суток Зона_суток1 { get; set; }
        public virtual Тариф Тариф { get; set; }
        public virtual Тариф Тариф1 { get; set; }
    }
}
